Fix the identification of vbmeta partition
After dynamic partition, vbmeta_system and vbemta_vendor partitions
are added. Therefore, partitions with 'vbmeta' prefix should be treated
as vbmeta partition.

This makes libavb avoid locating avb footer from the end of vbmeta_*
partitions. And will not emit the following error message, which could
be confusing even if the following read from the beginning succeeds.

Error message while loading vbmeta_system:
-----------------------------------
avb_slot_verify.c:481: DEBUG: Loading vbmeta struct from partition 'vbmeta_a'.
avb_footer.c:41: ERROR: Footer magic is incorrect.
avb_slot_verify.c:453: DEBUG: vbmeta_system_a: No footer detected.
-----------------------------------

Bug: b/134989217
Test: device launch, verify vbmeta, vbmeta_system, vbmeta_vendor.
Test: atest libavb_host_unittest
Change-Id: Ib0c2cd56197508fef8c12985e8cc0cd79469556c