Update patch set 1
Patch Set 1:

You are right, img2simg was not in PATH. fec is there but still there are fails:
[  PASSED  ] 99 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] AvbToolTest.AddHashtreeFooterFEC
[  FAILED  ] AvbToolTest.AddHashtreeFooterFECSparse
[  FAILED  ] AvbToolTest.AddHashtreeFooterCalcMaxImageSizeWithFEC

Error:
[ RUN      ] AvbToolTest.AddHashtreeFooterFECSparse
Traceback (most recent call last):
  File "./avbtool", line 2819, in <module>
    tool.run(sys.argv)
  File "./avbtool", line 2754, in run
    args.func(args)
  File "./avbtool", line 2802, in add_hashtree_footer
    args.calc_max_image_size)
  File "./avbtool", line 2355, in add_hashtree_footer
    fec_data = generate_fec_data(image_filename, fec_num_roots)
  File "./avbtool", line 2497, in generate_fec_data
    raise ValueError('Unexpected magic in FEC footer')
ValueError: Unexpected magic in FEC footer
external/avb/test/avbtool_unittest.cc:698: Failure
Value of: 0
Expected: ((((*(int *) &(rc))) & 0xff00) >> 8)
Which is: 1
./avbtool: Given image does not look like a vbmeta image.
external/avb/test/avb_unittest_util.h:113: Failure
Value of: 0
Expected: ((((*(int *) &(rc))) & 0xff00) >> 8)
Which is: 1
external/avb/test/avbtool_unittest.cc:730: Failure
Value of: InfoImage(rootfs_path)
  Actual: ""

Patch-set: 1