Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> Can someone explain why this is needed? As far as I know, libavb is already used by other modules (for example, fs_mgr) and that works just fine without this change.

Hi David,
That's because 'fastboot' has windows host output: fastboot.exe.
i.e., it has the following but "libavb" doesn't, which leads to a build error

"libfastboot":
        windows: {                                                              
            enabled: true,                                                                                                                                                   
        },  

error: system/core/fastboot/Android.bp:216:1: module "libfastboot" variant "windows_x86_static": depends on disabled module "libavb"   


Note: fs_mgr doesn't have windows host so it doesn't have this issue with libavb.

The alternative is to add windows: { enabled: true, } for "libavb" as well.
However, what 'libfastboot' needs is actually just avb headers (not libavb implementation).

cc_library_headers is provided by enh@ at aosp/1109273:

Elliott Hughes
Patch Set 1:

if you only need constants from the header, remember that
cc_library_headers is also an option.

I'm ok with either of both solutions.
Let me know WDYT.

Thanks!

Patch-set: 2
Reviewer: Gerrit User 1080813 <1080813@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0