Update patch set 5
Patch Set 5:

Oops, hit unit test failure, because it skips to try loading vbmeta from /boot.
Might need to think of a solution for that.

[ RUN      ] AvbSlotVerifyTest.NoVBMetaPartition
Error getting size of file '/tmp/libavb-tests.Tz9D3n/vbmeta.img'
avb_slot_verify.c:649: ERROR: vbmeta: Error loading footer.
external/avb/test/avb_slot_verify_unittest.cc:2437: Failure
Expected equality of these values:
  AVB_SLOT_VERIFY_RESULT_OK
    Which is: 0
  avb_slot_verify(ops_.avb_ops(), requested_partitions, "", AVB_SLOT_VERIFY_FLAGS_NONE, AVB_HASHTREE_ERROR_MODE_RESTART_AND_INVALIDATE, &slot_data)                         
    Which is: 2
external/avb/test/avb_slot_verify_unittest.cc:2438: Failure
Expected: (nullptr) != (slot_data), actual: (nullptr) vs NULL
Segmentation fault

Patch-set: 5
Reviewer: Gerrit User 1080813 <1080813@85c56323-6fa9-3386-8a01-6480fb634889>